#include "stationsreader.h"

#include <QDebug>

namespace {
const std::vector<Station> stationData{
    {QString("Radio Record"), QString("Radio Record.svg"), QUrl("http://eptop128.streamr.ru")},
    {QString("Mars Radio"), QString("Mars Radio.svg"), QUrl("http://mp3128.light.streamr.ru")},
    {QString("Deep"), QString("Deep.svg"), QUrl("http://mp3128.new.streamr.ru")},
    {QString("Веснушка FM"), QString("Веснушка FM.svg"), QUrl("http://eprnb128.streamr.ru")},
    {QString("Gold"), QString("Gold.svg"), QUrl("http://mp3128.residance.streamr.ru")},
    {QString("Innocence"), QString("Innocence.svg"), QUrl("http://air.radiorecord.ru:805/ibiza_320")},
    {QString("Маятник Фуко"), QString("Маятник Фуко.svg"), QUrl("http://air.radiorecord.ru:805/mf_320")},
    {QString("Electro"), QString("Electro.svg"), QUrl("http://air.radiorecord.ru:805/elect_320")},
    {QString("Midtempo"), QString("Midtempo.svg"), QUrl("http://air.radiorecord.ru:805/mt_320")},
    {QString("Bass House"), QString("Bass House.svg"), QUrl("http://air.radiorecord.ru:805/jackin_320")},
    {QString("Progressive"), QString("Progressive.svg"), QUrl("http://air.radiorecord.ru:805/progr_320")},
    {QString("Synthwave"), QString("Synthwave.svg"), QUrl("http://air.radiorecord.ru:805/synth_320")},
    {QString("House Hits"), QString("House Hits.svg"), QUrl("http://air.radiorecord.ru:805/househits_320")},
    {QString("Big Hits"), QString("Big Hits.svg"), QUrl("http://air.radiorecord.ru:805/bighits_320")},
    {QString("Dream Dance"), QString("Dream Dance.svg"), QUrl("http://air.radiorecord.ru:805/dream_320")},
    {QString("Darkside"), QString("Darkside.svg"), QUrl("http://air.radiorecord.ru:805/darkside_320")},
    {QString("Uplifting"), QString("Uplifting.svg"), QUrl("http://air.radiorecord.ru:805/uplift_320")},
    {QString("House Classics"), QString("House Classics.svg"), QUrl("http://air.radiorecord.ru:805/houseclss_320")},
    {QString("EDM Hits"), QString("EDM Hits.svg"), QUrl("http://air.radiorecord.ru:805/edmhits_320")},
    {QString("Neurofunk"), QString("Neurofunk.svg"), QUrl("http://air.radiorecord.ru:805/neurofunk_320")},
    {QString("Tecktonik"), QString("Tecktonik.svg"), QUrl("http://air.radiorecord.ru:805/tecktonik_320")},
    {QString("2-step"), QString("2-step.svg"), QUrl("http://air.radiorecord.ru:805/2step_320")},
    {QString("Trance Hits"), QString("Trance Hits.svg"), QUrl("http://air.radiorecord.ru:805/trancehits_320")},
    {QString("Rap Hits"), QString("Rap Hits.svg"), QUrl("http://air.radiorecord.ru:805/rap_320")},
    {QString("Rap Classics"), QString("Rap Classics.svg"), QUrl("http://air.radiorecord.ru:805/rapclassics_320")},
    {QString("Cadillac"), QString("Cadillac.svg"), QUrl("http://air.radiorecord.ru:805/cadillac_320")},
    {QString("1980-е"), QString("1980-е.svg"), QUrl("http://air.radiorecord.ru:805/1980_320")},
    {QString("Chill House"), QString("Chill House.svg"), QUrl("http://air.radiorecord.ru:805/chillhouse_320")},
    {QString("1970-е"), QString("1970-е.svg"), QUrl("http://air.radiorecord.ru:805/1970_320")},
    {QString("Complextro"), QString("Complextro.svg"), QUrl("http://air.radiorecord.ru:805/complextro_320")},
    {QString("Groove Tribal"), QString("Groove Tribal.svg"), QUrl("http://air.radiorecord.ru:805/groovetribal_320")},
    {QString("Russian Hits"), QString("Russian Hits.svg"), QUrl("http://air.radiorecord.ru:805/russianhits_320")},
    {QString("Megamix"), QString("Megamix.svg"), QUrl("http://air.radiorecord.ru:805/mix_320")},
    {QString("Jungle"), QString("Jungle.svg"), QUrl("http://air.radiorecord.ru:805/jungle_320")},
    {QString("Liquid Funk"), QString("Liquid Funk.svg"), QUrl("http://air.radiorecord.ru:805/liquidfunk_320")},
    {QString("Drum'n'Bass Hits"), QString("Drum'n'Bass Hits.svg"), QUrl("http://air.radiorecord.ru:805/drumhits_320")},
    {QString("Russian Gold"), QString("Russian Gold.svg"), QUrl("http://air.radiorecord.ru:805/russiangold_320")},
    {QString("Eurodance"), QString("Eurodance.svg"), QUrl("http://air.radiorecord.ru:805/eurodance_320")},
    {QString("Technopop"), QString("Technopop.svg"), QUrl("http://air.radiorecord.ru:805/technopop_320")},
    {QString("Disco Func"), QString("Disco Func.svg"), QUrl("http://air.radiorecord.ru:805/discofunk_320")},
    {QString("EDM"), QString("EDM.svg"), QUrl("http://air.radiorecord.ru:805/club_320")},
    {QString("Tropical"), QString("Tropical.svg"), QUrl("http://air.radiorecord.ru:805/trop_320")},
    {QString("GOA PSY"), QString("GOA PSY.svg"), QUrl("http://air.radiorecord.ru:805/goa_320")},
    {QString("Future House"), QString("Future House.svg"), QUrl("http://air.radiorecord.ru:805/fut_320")},
    {QString("Trancemission"), QString("Trancemission.svg"), QUrl("http://air.radiorecord.ru:805/tm_320")},
    {QString("Chill-Out"), QString("Chill-Out.svg"), QUrl("http://air.radiorecord.ru:805/chil_320")},
    {QString("Minimal Tech"), QString("Minimal Tech.svg"), QUrl("http://air.radiorecord.ru:805/mini_320")},
    {QString("Pirate Station"), QString("Pirate Station.svg"), QUrl("http://air.radiorecord.ru:805/ps_320")},
    {QString("Russian Mix"), QString("Russian Mix.svg"), QUrl("http://air.radiorecord.ru:805/rus_320")},
    {QString("Vip House"), QString("Vip House.svg"), QUrl("http://air.radiorecord.ru:805/vip_320")},
    {QString("Дискотека 90"), QString("Дискотека 90.svg"), QUrl("http://air.radiorecord.ru:805/sd90_320")},
    {QString("Moombahton"), QString("Moombahton.svg"), QUrl("http://air.radiorecord.ru:805/mmbt_320")},
    {QString("Trancehouse"), QString("Trancehouse.svg"), QUrl("http://air.radiorecord.ru:805/trancehouse_320")},
    {QString("Hypnotic"), QString("Hypnotic.svg"), QUrl("http://air.radiorecord.ru:805/hypno_320")},
    {QString("Breaks"), QString("Breaks.svg"), QUrl("http://air.radiorecord.ru:805/brks_320")},
    {QString("Dubstep"), QString("Dubstep.svg"), QUrl("http://air.radiorecord.ru:805/dub_320")},
    {QString("Dancecore"), QString("Dancecore.svg"), QUrl("http://air.radiorecord.ru:805/dc_320")},
    {QString("Techno"), QString("Techno.svg"), QUrl("http://air.radiorecord.ru:805/techno_320")},
    {QString("Remix"), QString("Remix.svg"), QUrl("http://air.radiorecord.ru:805/rmx_320")},
    {QString("Future Bass"), QString("Future Bass.svg"), QUrl("http://air.radiorecord.ru:805/fbass_320")},
    {QString("Hardstyle"), QString("Hardstyle.svg"), QUrl("http://air.radiorecord.ru:805/teo_320")},
    {QString("Hard Bass"), QString("Hard Bass.svg"), QUrl("http://air.radiorecord.ru:805/hbass_320")},
    {QString("Trap"), QString("Trap.svg"), QUrl("http://air.radiorecord.ru:805/trap_320")},
    {QString("Old School"), QString("Old School.svg"), QUrl("http://air.radiorecord.ru:805/pump_320")},
    {QString("Rock"), QString("Rock.svg"), QUrl("http://air.radiorecord.ru:805/rock_320")},
    {QString("Медляк FM"), QString("Медляк FM.svg"), QUrl("http://air.radiorecord.ru:805/mdl_320")},
    {QString("Гоп FM"), QString("Гоп FM.svg"), QUrl("http://air.radiorecord.ru:805/gop_320")},
    {QString("Симфония FM"), QString("Симфония FM.svg"), QUrl("http://air.radiorecord.ru:805/symph_320")},
    {QString("Black"), QString("Black.svg"), QUrl("http://air.radiorecord.ru:805/yo_320")},
    {QString("Rave FM"), QString("Rave FM.svg"), QUrl("http://air.radiorecord.ru:805/rave_320")},
    {QString("Гастарбайтер FM"), QString("Гастарбайтер FM.svg"), QUrl("http://air.radiorecord.ru:805/gast_320")},
    {QString("Нафталин FM"), QString("Нафталин FM.svg"), QUrl("http://air.radiorecord.ru:805/naft_320")},
    {QString("Аншлаг FM"), QString("Аншлаг FM.svg"), QUrl("http://air.radiorecord.ru:805/ansh_320")}};
}

std::pair<bool, std::vector<Station>> StationsReader::requestStationsReader()
{
    return std::make_pair(true, stationData);
}
